const ATLETAS = [
  {
    "nome": "Adriana Teixeira Dos Santos",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "27/06/2026",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Dale Runners",
    "busca": "adriana teixeira dos santos"
  },
  {
    "nome": "Adriely Barbosa Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "30/09/1997",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Gogorunners",
    "busca": "adriely barbosa da silva"
  },
  {
    "nome": "Agricyanna De Moura Castro Reges",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "23/12/1984",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "agricyanna de moura castro reges"
  },
  {
    "nome": "Aldenice Lima De Sousa",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "08/09/1991",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "aldenice lima de sousa"
  },
  {
    "nome": "Aldirene Silva Dos Santos",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "13/09/1987",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "aldirene silva dos santos"
  },
  {
    "nome": "Aleia Alves De Carvalho",
    "categoria": "Master B - 5KM - 50 anos acima",
    "grupo": "Master 50+",
    "sexo": "Feminino",
    "nascimento": "24/11/1957",
    "camisa": "GG",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "aleia alves de carvalho"
  },
  {
    "nome": "Alex Cristian Oeiras Barata",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "11/07/1981",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "alex cristian oeiras barata"
  },
  {
    "nome": "Alexandra Fernandes De Assis",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "18/11/1983",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runneres",
    "busca": "alexandra fernandes de assis"
  },
  {
    "nome": "Alexandre Da Silva Ferreira",
    "categoria": "Sub-13 - 1KM - até 13 anos",
    "grupo": "Kids 13 ANOS 1KM",
    "sexo": "Masculino",
    "nascimento": "06/05/2017",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Gogorunnrs",
    "busca": "alexandre da silva ferreira"
  },
  {
    "nome": "Alexssandra De Sousa Martins",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "23/10/2000",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Estação Fitness",
    "busca": "alexssandra de sousa martins"
  },
  {
    "nome": "Alice Emanuelle Monteiro Soares",
    "categoria": "Sub-13 - 1KM - até 13 anos",
    "grupo": "Kids 13 ANOS 1KM",
    "sexo": "Feminino",
    "nascimento": "21/02/2013",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runneres",
    "busca": "alice emanuelle monteiro soares"
  },
  {
    "nome": "Aliene Pinheiro De Araujo Santiago",
    "categoria": "Master B - 5KM - 50 anos acima",
    "grupo": "Master 50+",
    "sexo": "Feminino",
    "nascimento": "28/11/1975",
    "camisa": "GG",
    "representaEquipe": "Sim",
    "equipe": "Corre Rio",
    "busca": "aliene pinheiro de araujo santiago"
  },
  {
    "nome": "Alisson Fernandes Soares",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "29/11/1997",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Dudu_Do_Pará",
    "busca": "alisson fernandes soares"
  },
  {
    "nome": "Altamir Crispim Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "03/10/1984",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "altamir crispim silva"
  },
  {
    "nome": "Alyson De Oliveira Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "05/05/2001",
    "camisa": "G",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "alyson de oliveira silva"
  },
  {
    "nome": "Ana Carolina Alencar Rodrigues",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Feminino",
    "nascimento": "13/04/2011",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runneres",
    "busca": "ana carolina alencar rodrigues"
  },
  {
    "nome": "Ana Cláudia Dos Santos Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "03/01/1990",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Rose Training Academia Rum Delas",
    "busca": "ana claudia dos santos silva"
  },
  {
    "nome": "Ana Gabriela Soares Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "06/02/2004",
    "camisa": "XG",
    "representaEquipe": "Não",
    "equipe": "Sem Atividade Física",
    "busca": "ana gabriela soares silva"
  },
  {
    "nome": "Ana Karolyna Teixeira",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "14/11/1995",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Studio Jp",
    "busca": "ana karolyna teixeira"
  },
  {
    "nome": "Ana Laura De Castro Laranjeira",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Feminino",
    "nascimento": "18/08/2010",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Equipe Jp",
    "busca": "ana laura de castro laranjeira"
  },
  {
    "nome": "Ana Paula De Limas Cardoso",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "31/05/1998",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Gogó Runners",
    "busca": "ana paula de limas cardoso"
  },
  {
    "nome": "Ana Sousa Pereira",
    "categoria": "Master B - 5KM - 50 anos acima",
    "grupo": "Master 50+",
    "sexo": "Feminino",
    "nascimento": "25/05/1975",
    "camisa": "G",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "ana sousa pereira"
  },
  {
    "nome": "Anderson Brito Dos Santos",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "05/02/1988",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Jp",
    "busca": "anderson brito dos santos"
  },
  {
    "nome": "André Luiz De Sá",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "11/07/1984",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Studio Jump Alta Performance",
    "busca": "andre luiz de sa"
  },
  {
    "nome": "Andréia Bezerra Silva Rocha",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "01/08/1984",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Studio Jump Alta Performance",
    "busca": "andreia bezerra silva rocha"
  },
  {
    "nome": "Andreia Lucia Daniel",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "12/08/1979",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runmers",
    "busca": "andreia lucia daniel"
  },
  {
    "nome": "Andressa Camargo Cabral",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "08/08/2001",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Studio Jp",
    "busca": "andressa camargo cabral"
  },
  {
    "nome": "Andreza Caroline Azevedo Rodrigues",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "19/01/1995",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Gogóruners",
    "busca": "andreza caroline azevedo rodrigues"
  },
  {
    "nome": "Anna Rayssa Silva De Souza",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "22/05/2006",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Não informado",
    "busca": "anna rayssa silva de souza"
  },
  {
    "nome": "Anny Gabrielly Chaves Rodrigues",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "12/06/2007",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "anny gabrielly chaves rodrigues"
  },
  {
    "nome": "Antônia Da Silva Lima Lacerda",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "19/12/1981",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "antonia da silva lima lacerda"
  },
  {
    "nome": "Antonio Fernandes Silva",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "29/07/1979",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "antonio fernandes silva"
  },
  {
    "nome": "Antonio Kennedy De Sousa Lima",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "18/10/1985",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Biocorredores",
    "busca": "antonio kennedy de sousa lima"
  },
  {
    "nome": "Araujo.M.Sandra86@Gmail.Com",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "25/02/1986",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Estação Fitness",
    "busca": "araujo m sandra86 gmail com"
  },
  {
    "nome": "Arthur Francisco Branquinho Do Nascimento",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Masculino",
    "nascimento": "03/12/2008",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "arthur francisco branquinho do nascimento"
  },
  {
    "nome": "Arthur Ribeiro Silva",
    "categoria": "Sub-13 - 1KM - até 13 anos",
    "grupo": "Kids 13 ANOS 1KM",
    "sexo": "Masculino",
    "nascimento": "21/01/2020",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Gogórunners",
    "busca": "arthur ribeiro silva"
  },
  {
    "nome": "Ben Hur Marinho De Oliveira",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "18/05/2006",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Corredores De São José",
    "busca": "ben hur marinho de oliveira"
  },
  {
    "nome": "Benjamin Daniel Da Silva Ferreira",
    "categoria": "Sub-13 - 1KM - até 13 anos",
    "grupo": "Kids 13 ANOS 1KM",
    "sexo": "Masculino",
    "nascimento": "16/01/2017",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Gogó Runers",
    "busca": "benjamin daniel da silva ferreira"
  },
  {
    "nome": "Bernardo Dias De Souza",
    "categoria": "Sub-13 - 1KM - até 13 anos",
    "grupo": "Kids 13 ANOS 1KM",
    "sexo": "Masculino",
    "nascimento": "23/06/2018",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Dudu Do Para",
    "busca": "bernardo dias de souza"
  },
  {
    "nome": "Betânia Batista Da Silva Antunes",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "09/05/1982",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "betania batista da silva antunes"
  },
  {
    "nome": "Brígida Fernanda Chaves Rodrigues",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "27/12/2003",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "brigida fernanda chaves rodrigues"
  },
  {
    "nome": "Bruna Rodrigues Santana",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "10/05/2001",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "bruna rodrigues santana"
  },
  {
    "nome": "Bruno Leal Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "02/10/1995",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runers",
    "busca": "bruno leal da silva"
  },
  {
    "nome": "Bruno Vieira",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "08/08/1988",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Anti Social Running Club",
    "busca": "bruno vieira"
  },
  {
    "nome": "Caio Aguiar De Sousa",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "21/07/1999",
    "camisa": "G",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "caio aguiar de sousa"
  },
  {
    "nome": "Camila Eduardo De Souza",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "19/10/2000",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Corre Água Azul",
    "busca": "camila eduardo de souza"
  },
  {
    "nome": "Carleana Almeida Sales",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "07/05/1987",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Studi Jump Alta Performance",
    "busca": "carleana almeida sales"
  },
  {
    "nome": "Carliane Sousa Pires",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "12/04/1993",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "carliane sousa pires"
  },
  {
    "nome": "Carlos Eduardo Ferreira Araújo",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "17/07/2003",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Hyfit1000",
    "busca": "carlos eduardo ferreira araujo"
  },
  {
    "nome": "Caroline Nebo",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "31/01/1983",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Studio Jp",
    "busca": "caroline nebo"
  },
  {
    "nome": "Carolliny Lopes De Queiroz",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "31/08/2003",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Joubert Procópio",
    "busca": "carolliny lopes de queiroz"
  },
  {
    "nome": "Cecília Gomes Aires",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "23/12/2003",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "cecilia gomes aires"
  },
  {
    "nome": "Claudiane De Souza Faria",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "08/10/1992",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Studio Jp",
    "busca": "claudiane de souza faria"
  },
  {
    "nome": "Claudivan Barbosa De Oliveira",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "27/02/1984",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "claudivan barbosa de oliveira"
  },
  {
    "nome": "Cleide Rodrigues Da Silva",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "31/08/1984",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Studio Jump Alta Performance",
    "busca": "cleide rodrigues da silva"
  },
  {
    "nome": "Cleuma De Oliveira Mendanha Silva",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "02/02/1985",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "cleuma de oliveira mendanha silva"
  },
  {
    "nome": "Cristiane De Souza Faria",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "05/07/1986",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Studiojp  Jp",
    "busca": "cristiane de souza faria"
  },
  {
    "nome": "Cristiano Procópio De Oliveira",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "01/05/1981",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "cristiano procopio de oliveira"
  },
  {
    "nome": "Damaris Manoela",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "07/02/2003",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Fogo Runners",
    "busca": "damaris manoela"
  },
  {
    "nome": "Daniel Castro",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Masculino",
    "nascimento": "30/06/2008",
    "camisa": "G",
    "representaEquipe": "Não",
    "equipe": ".",
    "busca": "daniel castro"
  },
  {
    "nome": "Daniel Santiago Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "02/08/2003",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "daniel santiago da silva"
  },
  {
    "nome": "Daniela Felix Vaz",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "27/08/1998",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "daniela felix vaz"
  },
  {
    "nome": "Daniella De Sousa Costa Maia",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "26/06/1992",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "daniella de sousa costa maia"
  },
  {
    "nome": "Danielle Da Silva Moura",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "03/08/2003",
    "camisa": "G",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "danielle da silva moura"
  },
  {
    "nome": "Danila Barros Capellari",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "26/03/2026",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Academia Sparta",
    "busca": "danila barros capellari"
  },
  {
    "nome": "Dayane Da Silva Lima",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "15/05/1994",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Gogorunners",
    "busca": "dayane da silva lima"
  },
  {
    "nome": "Dayane Mendes Nicacio",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "04/07/1995",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Jb Joubert",
    "busca": "dayane mendes nicacio"
  },
  {
    "nome": "Dayane Prochera Batista",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "20/09/1992",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "dayane prochera batista"
  },
  {
    "nome": "Dayane Silva Ferreira",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "17/08/1992",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Jourbert",
    "busca": "dayane silva ferreira"
  },
  {
    "nome": "Débora Oliveira Nery",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "08/03/1998",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "debora oliveira nery"
  },
  {
    "nome": "Denise Andrade",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "16/12/1987",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Dudu_Do_Para",
    "busca": "denise andrade"
  },
  {
    "nome": "Diego Barbosa Chagas",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "16/02/1993",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "diego barbosa chagas"
  },
  {
    "nome": "Dina Charles Silva Marinho",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "08/10/1983",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "dina charles silva marinho"
  },
  {
    "nome": "Diomar Evangelista De Sousa",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "06/12/1988",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "One Run",
    "busca": "diomar evangelista de sousa"
  },
  {
    "nome": "Dione Silva Souza",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "24/09/2001",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "dione silva souza"
  },
  {
    "nome": "Douglas Daniel Ferreira",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "09/06/1997",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Gogórunners",
    "busca": "douglas daniel ferreira"
  },
  {
    "nome": "Edilene Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "16/05/1992",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "edilene silva"
  },
  {
    "nome": "Edilson Galdino Do Carmo",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "26/01/1985",
    "camisa": "GG",
    "representaEquipe": "Sim",
    "equipe": "Studio Jp",
    "busca": "edilson galdino do carmo"
  },
  {
    "nome": "Editania Menezes Dos Santos",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "13/10/1999",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Coyotes Running",
    "busca": "editania menezes dos santos"
  },
  {
    "nome": "Eduardo Moreira De Sousa",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "07/05/1993",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Dudu_Do_Para",
    "busca": "eduardo moreira de sousa"
  },
  {
    "nome": "Elaine Patrícia Pereira Almeida",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "05/08/1988",
    "camisa": "G",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "elaine patricia pereira almeida"
  },
  {
    "nome": "Eliane Maria Rodrigues Daniel",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "26/01/2026",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Gogó Runners",
    "busca": "eliane maria rodrigues daniel"
  },
  {
    "nome": "Emily Vitória Da Silva Ferreira",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "19/04/2012",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Gogorunners",
    "busca": "emily vitoria da silva ferreira"
  },
  {
    "nome": "Enzo Gabriel Da Cruz Cardoso",
    "categoria": "Sub-13 - 1KM - até 13 anos",
    "grupo": "Kids 13 ANOS 1KM",
    "sexo": "Masculino",
    "nascimento": "18/04/2013",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "enzo gabriel da cruz cardoso"
  },
  {
    "nome": "Erick Estivens Carvalho Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "20/11/1992",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogórunners",
    "busca": "erick estivens carvalho da silva"
  },
  {
    "nome": "Erika Dayanne Alves Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "05/11/1992",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "erika dayanne alves da silva"
  },
  {
    "nome": "Érika Figueiredo",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "18/02/1997",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "erika figueiredo"
  },
  {
    "nome": "Erika Kethellen De Araújo Ramos",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "05/06/2004",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "erika kethellen de araujo ramos"
  },
  {
    "nome": "Evanderson Ferreira De Souza Bento",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "01/01/1990",
    "camisa": "XG",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "evanderson ferreira de souza bento"
  },
  {
    "nome": "Ezia Batista De Faria",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "08/11/1993",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "One Rum",
    "busca": "ezia batista de faria"
  },
  {
    "nome": "Fabiano Da Cruz Rocha",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "15/05/1991",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Studio Jump Alta Performance",
    "busca": "fabiano da cruz rocha"
  },
  {
    "nome": "Fabrício De Sá Soares",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "12/08/1988",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "fabricio de sa soares"
  },
  {
    "nome": "Fabrício Leite Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "08/04/2001",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogó Runers",
    "busca": "fabricio leite silva"
  },
  {
    "nome": "Felipe Souza De Miranda",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "03/03/2005",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Studio Jp",
    "busca": "felipe souza de miranda"
  },
  {
    "nome": "Fernanda Da Silva Coelho",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "19/10/1996",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "fernanda da silva coelho"
  },
  {
    "nome": "Fernanda Santos De Assunção",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "19/09/1993",
    "camisa": "GG",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "fernanda santos de assuncao"
  },
  {
    "nome": "Flaukia Rodrigues De Moraes Das Neves",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "29/07/1992",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "flaukia rodrigues de moraes das neves"
  },
  {
    "nome": "Francinádia Pereira Santos",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "16/11/2000",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "francinadia pereira santos"
  },
  {
    "nome": "Francinalva Vieira De Carvalho",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "11/10/1982",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "francinalva vieira de carvalho"
  },
  {
    "nome": "Francisca Das Chagas Nunes Rodrigues",
    "categoria": "Master B - 5KM - 50 anos acima",
    "grupo": "Master 50+",
    "sexo": "Feminino",
    "nascimento": "14/08/1971",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "francisca das chagas nunes rodrigues"
  },
  {
    "nome": "Francisca Luzivania De Oliveira",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "22/08/1981",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "francisca luzivania de oliveira"
  },
  {
    "nome": "Francisco De Assis Santos Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "21/02/2001",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "francisco de assis santos da silva"
  },
  {
    "nome": "Francisco Wagner Araújo Barros",
    "categoria": "Master B - 5KM - 50 anos acima",
    "grupo": "Master 50+",
    "sexo": "Masculino",
    "nascimento": "02/05/1976",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "francisco wagner araujo barros"
  },
  {
    "nome": "Gildo Cruz Pereira",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "23/07/1978",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Corredores De São José",
    "busca": "gildo cruz pereira"
  },
  {
    "nome": "Gisele De Sousa Coelho",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "27/06/2026",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Studio Jp",
    "busca": "gisele de sousa coelho"
  },
  {
    "nome": "Guilherme Calaço De Oliveira",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "10/12/2002",
    "camisa": "GG",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "guilherme calaco de oliveira"
  },
  {
    "nome": "Guilherme Farias Saldanha",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "16/03/2000",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "guilherme farias saldanha"
  },
  {
    "nome": "Hayanna Ribeiro",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "14/01/1991",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Nao",
    "busca": "hayanna ribeiro"
  },
  {
    "nome": "Helio Damaceno Júnior",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "11/09/2003",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Equipe Jp",
    "busca": "helio damaceno junior"
  },
  {
    "nome": "Hellen Karoline Landin Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "20/07/1997",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Gogó Runners",
    "busca": "hellen karoline landin da silva"
  },
  {
    "nome": "Heloísa Karolay De Andrade Rodrigues",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "23/08/2003",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "heloisa karolay de andrade rodrigues"
  },
  {
    "nome": "Higor De Sousa Batista",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "01/02/2006",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "higor de sousa batista"
  },
  {
    "nome": "Hugo Ayalla Menezes",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "09/05/2002",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Endorfina1000",
    "busca": "hugo ayalla menezes"
  },
  {
    "nome": "Iara Lima Monteiro",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "10/01/1993",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "iara lima monteiro"
  },
  {
    "nome": "Idelvino Guilherme Do Nascimento Santos",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "22/04/2001",
    "camisa": "GG",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "idelvino guilherme do nascimento santos"
  },
  {
    "nome": "Ingrid Arruda Ribeiro Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "19/10/1998",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "ingrid arruda ribeiro silva"
  },
  {
    "nome": "Ionara Gomes Brito",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "10/10/1978",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Studio Jump Alta Performance",
    "busca": "ionara gomes brito"
  },
  {
    "nome": "Iraque Soares Rocha",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "19/05/2006",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogó Runners",
    "busca": "iraque soares rocha"
  },
  {
    "nome": "Irisvania Brasil Sousa",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "25/10/1993",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "irisvania brasil sousa"
  },
  {
    "nome": "Isadora Dorta Lima",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Feminino",
    "nascimento": "22/04/2010",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "isadora dorta lima"
  },
  {
    "nome": "Ivana Dos Santos Monteiro",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "28/12/1986",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "ivana dos santos monteiro"
  },
  {
    "nome": "Jaci Dorta Da Silva Aragão",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "10/10/1984",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "jaci dorta da silva aragao"
  },
  {
    "nome": "Jakeline Chaves De Mendonça",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "22/02/1994",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Corre Rio",
    "busca": "jakeline chaves de mendonca"
  },
  {
    "nome": "Jaquison Andrade",
    "categoria": "Master B - 5KM - 50 anos acima",
    "grupo": "Master 50+",
    "sexo": "Masculino",
    "nascimento": "10/08/1960",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Corredores De São José",
    "busca": "jaquison andrade"
  },
  {
    "nome": "Jarder Da Silva Marinho",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "18/11/1987",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runers",
    "busca": "jarder da silva marinho"
  },
  {
    "nome": "Jariciane Cruz Setubal",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "04/03/1983",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Dudu Do Para",
    "busca": "jariciane cruz setubal"
  },
  {
    "nome": "Jéssica De Lima Alves",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "08/09/1993",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "jessica de lima alves"
  },
  {
    "nome": "Joanice Lemes Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "28/07/1995",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Corre Rio",
    "busca": "joanice lemes da silva"
  },
  {
    "nome": "João Dionilio Maximiano Araújo",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "07/02/2006",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Studio Jp",
    "busca": "joao dionilio maximiano araujo"
  },
  {
    "nome": "João Gabriel De Lima Cruz",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "29/07/2007",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "joao gabriel de lima cruz"
  },
  {
    "nome": "João Machado",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "11/04/1995",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Studio Jump Alta Perfromance",
    "busca": "joao machado"
  },
  {
    "nome": "João Paulo Da Silva Pires",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "02/04/2008",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "joao paulo da silva pires"
  },
  {
    "nome": "João Pedro Alves Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "11/05/2008",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogórunnes",
    "busca": "joao pedro alves da silva"
  },
  {
    "nome": "João Pedro Alves Rodrigues",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "04/06/2008",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "joao pedro alves rodrigues"
  },
  {
    "nome": "João Raphael De Souza Cunha",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Masculino",
    "nascimento": "28/11/2011",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não",
    "busca": "joao raphael de souza cunha"
  },
  {
    "nome": "João Vitor De Oliveira Sousa",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "08/08/2005",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "joao vitor de oliveira sousa"
  },
  {
    "nome": "Jonas Almeida Silva",
    "categoria": "Sub-13 - 1KM - até 13 anos",
    "grupo": "Kids 13 ANOS 1KM",
    "sexo": "Masculino",
    "nascimento": "14/04/2020",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "jonas almeida silva"
  },
  {
    "nome": "Josilene Batista Corrêa Borges",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "30/06/1981",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Rose Training Run Delas",
    "busca": "josilene batista correa borges"
  },
  {
    "nome": "Josué Chaves Reis",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "09/11/2004",
    "camisa": "XG",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "josue chaves reis"
  },
  {
    "nome": "Juarez Ramos De Brito Júnior",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "18/01/1984",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Studio Jump Alta Performance",
    "busca": "juarez ramos de brito junior"
  },
  {
    "nome": "Júlia Sousa Bezerra",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "28/10/2006",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Elite Run",
    "busca": "julia sousa bezerra"
  },
  {
    "nome": "Juliete Barbosa Miranda",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "04/06/1995",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Corre Rio",
    "busca": "juliete barbosa miranda"
  },
  {
    "nome": "Kamily Dos Santos Vieira",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "19/04/2006",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Jp",
    "busca": "kamily dos santos vieira"
  },
  {
    "nome": "Kaylane De Souza Galdino",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "08/02/2003",
    "camisa": "G",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "kaylane de souza galdino"
  },
  {
    "nome": "Kesia Rutielly Moreira Gomes",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "25/11/2001",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "kesia rutielly moreira gomes"
  },
  {
    "nome": "Kethllen Caroliny De Sousa Fonseca",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "04/02/1999",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Elas No Pace",
    "busca": "kethllen caroliny de sousa fonseca"
  },
  {
    "nome": "Khauan Victor Rodrigues De Souza",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Masculino",
    "nascimento": "30/06/2009",
    "camisa": "GG",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "khauan victor rodrigues de souza"
  },
  {
    "nome": "Laila Cristine Limeira Caldas",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "26/12/1988",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Academia Sparta",
    "busca": "laila cristine limeira caldas"
  },
  {
    "nome": "Lais Kalinny Das Chagas Lima Galvão",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Feminino",
    "nascimento": "25/11/2009",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Dudu_Do_Pará",
    "busca": "lais kalinny das chagas lima galvao"
  },
  {
    "nome": "Lallumy Gabriela Soares De Oliveira",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "29/06/1995",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Corre Água Azul",
    "busca": "lallumy gabriela soares de oliveira"
  },
  {
    "nome": "Larissa Mariana Costa",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "05/10/1993",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Studio Jump Alta Performance",
    "busca": "larissa mariana costa"
  },
  {
    "nome": "Lauana Alves Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "30/11/2004",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Runbora Canaã",
    "busca": "lauana alves da silva"
  },
  {
    "nome": "Lauany Vitória De Melo Teixeira",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Feminino",
    "nascimento": "07/07/2010",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "lauany vitoria de melo teixeira"
  },
  {
    "nome": "Lauriele Machado De Sousa",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "01/11/1992",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Jean Orientarista",
    "busca": "lauriele machado de sousa"
  },
  {
    "nome": "Lázaro Filipe Do Nascimento Santos",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "10/07/1993",
    "camisa": "G",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "lazaro filipe do nascimento santos"
  },
  {
    "nome": "Leila Das Neves Roseno",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "01/12/1987",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "leila das neves roseno"
  },
  {
    "nome": "Leiliane Pereira Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "07/05/2002",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "leiliane pereira da silva"
  },
  {
    "nome": "Leo De Morais Magalhães",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "28/08/2006",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogorunners",
    "busca": "leo de morais magalhaes"
  },
  {
    "nome": "Leonardo Reis De Sousa Aguiar",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "06/01/2026",
    "camisa": "GG",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "leonardo reis de sousa aguiar"
  },
  {
    "nome": "Letícia Almeida",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "17/06/2002",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "leticia almeida"
  },
  {
    "nome": "Letícia Nunes Rodrigues",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "30/05/1992",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "leticia nunes rodrigues"
  },
  {
    "nome": "Letícia Rodrigues Daniel",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "05/10/2004",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Gogó Runners",
    "busca": "leticia rodrigues daniel"
  },
  {
    "nome": "Lidia Lígia De Oliveira Silva",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "21/10/1984",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Dudu_Do_Para",
    "busca": "lidia ligia de oliveira silva"
  },
  {
    "nome": "Luana Caetano Coelho",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "15/08/1996",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Dudu Do Para",
    "busca": "luana caetano coelho"
  },
  {
    "nome": "Luana Costa De Souza",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "02/07/1996",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "luana costa de souza"
  },
  {
    "nome": "Lucas Almeida Silva",
    "categoria": "Sub-13 - 1KM - até 13 anos",
    "grupo": "Kids 13 ANOS 1KM",
    "sexo": "Feminino",
    "nascimento": "24/07/2018",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "lucas almeida silva"
  },
  {
    "nome": "Lucas De Moura Reges",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Masculino",
    "nascimento": "07/08/2009",
    "camisa": "G",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "lucas de moura reges"
  },
  {
    "nome": "Lucas Emanuel Reis Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "23/04/2000",
    "camisa": "G",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "lucas emanuel reis da silva"
  },
  {
    "nome": "Lucas Gabriel De Sousa Santos",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "30/04/1999",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runner",
    "busca": "lucas gabriel de sousa santos"
  },
  {
    "nome": "Lucas Nazaré Miranda",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "11/04/1995",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Gogorunnersoficial",
    "busca": "lucas nazare miranda"
  },
  {
    "nome": "Lucas Souza Miranda",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Masculino",
    "nascimento": "19/06/2009",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Studio Jp",
    "busca": "lucas souza miranda"
  },
  {
    "nome": "Lucilene Dos Santos Barbosa",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "13/09/1991",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Corre Água  Azul",
    "busca": "lucilene dos santos barbosa"
  },
  {
    "nome": "Lucilene Pinto Moreira",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "24/07/1977",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Corre Água Azul",
    "busca": "lucilene pinto moreira"
  },
  {
    "nome": "Luelen Santos",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "03/06/1997",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "luelen santos"
  },
  {
    "nome": "Luingrid Lopes Sousa",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "27/07/2000",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Dudu_Do_Para",
    "busca": "luingrid lopes sousa"
  },
  {
    "nome": "Luis Felipe Rodrigues De Oliveira",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Masculino",
    "nascimento": "19/01/2011",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Studio Jump Alta Performance",
    "busca": "luis felipe rodrigues de oliveira"
  },
  {
    "nome": "Luís Gustavo Da Cruz Cardoso",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Masculino",
    "nascimento": "26/08/2011",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "luis gustavo da cruz cardoso"
  },
  {
    "nome": "Luiz Gabriel Da Silva",
    "categoria": "Sub-13 - 1KM - até 13 anos",
    "grupo": "Kids 13 ANOS 1KM",
    "sexo": "Masculino",
    "nascimento": "10/05/2026",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "luiz gabriel da silva"
  },
  {
    "nome": "Luiz Otávio Soares Da Silva",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Masculino",
    "nascimento": "06/03/2009",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "luiz otavio soares da silva"
  },
  {
    "nome": "Luzia Alves Da Silva Barros",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "03/12/1979",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "luzia alves da silva barros"
  },
  {
    "nome": "Luzia Silva Rocha",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "09/09/1995",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "luzia silva rocha"
  },
  {
    "nome": "Maiara Alves Da Silva Daniel",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "20/07/1989",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogórunners",
    "busca": "maiara alves da silva daniel"
  },
  {
    "nome": "Manoel Moura Das Chagas Filho",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "28/09/1985",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Wd Running Division",
    "busca": "manoel moura das chagas filho"
  },
  {
    "nome": "Marcela De Carvalho Câmara",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "26/02/1992",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "marcela de carvalho camara"
  },
  {
    "nome": "Marcelo Vinicius",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "05/12/1985",
    "camisa": "GG",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "marcelo vinicius"
  },
  {
    "nome": "Marcivania Araujo Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "04/10/1999",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Runners Fda",
    "busca": "marcivania araujo da silva"
  },
  {
    "nome": "Marcus Vinícius Andrade Dos Santos",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "27/09/1976",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "marcus vinicius andrade dos santos"
  },
  {
    "nome": "Mareça Santos Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "27/01/1998",
    "camisa": "G",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "mareca santos da silva"
  },
  {
    "nome": "Maria Clara Coelho Guimarães",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Feminino",
    "nascimento": "12/12/2009",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Studio Jp",
    "busca": "maria clara coelho guimaraes"
  },
  {
    "nome": "Maria Daniela De Souza Noleto",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "29/06/1986",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "maria daniela de souza noleto"
  },
  {
    "nome": "Maria Do Socorro Gomes Da Costa",
    "categoria": "Master B - 5KM - 50 anos acima",
    "grupo": "Master 50+",
    "sexo": "Feminino",
    "nascimento": "26/12/2026",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "maria do socorro gomes da costa"
  },
  {
    "nome": "Maria Domingas Dos Santos Barbosa",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "17/10/1976",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Rose Academia",
    "busca": "maria domingas dos santos barbosa"
  },
  {
    "nome": "Maria Eduarda De Sousa Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "23/02/2005",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não",
    "busca": "maria eduarda de sousa silva"
  },
  {
    "nome": "Maria Eduarda Ferreira Rodrigues",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "05/12/2004",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "maria eduarda ferreira rodrigues"
  },
  {
    "nome": "Maria Eduarda Grassi Valadão",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "14/11/2003",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "maria eduarda grassi valadao"
  },
  {
    "nome": "Maria Elionete De Jesus Itacaramby",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "08/01/1984",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Corrida Das Musas",
    "busca": "maria elionete de jesus itacaramby"
  },
  {
    "nome": "Maria Helena Souza Reis",
    "categoria": "Sub-13 - 1KM - até 13 anos",
    "grupo": "Kids 13 ANOS 1KM",
    "sexo": "Feminino",
    "nascimento": "16/05/2017",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Jp",
    "busca": "maria helena souza reis"
  },
  {
    "nome": "Maria José Teixeira Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "15/09/2026",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogorunners",
    "busca": "maria jose teixeira da silva"
  },
  {
    "nome": "Maria Luiza Dorta Aragão",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Feminino",
    "nascimento": "21/11/2010",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "maria luiza dorta aragao"
  },
  {
    "nome": "Maria Safira De Sousa Coimbra",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "04/01/2002",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogorunnes",
    "busca": "maria safira de sousa coimbra"
  },
  {
    "nome": "Maria Sandra Do Nascimento",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "03/04/1991",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "maria sandra do nascimento"
  },
  {
    "nome": "Mariana Carneiro Coimbra",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "10/02/2006",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "mariana carneiro coimbra"
  },
  {
    "nome": "Mariana Souza Dos Santos",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "07/05/2004",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogórunners",
    "busca": "mariana souza dos santos"
  },
  {
    "nome": "Marina Alves Da Silva Lima",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "04/07/1980",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Biocorredores",
    "busca": "marina alves da silva lima"
  },
  {
    "nome": "Marivania Dos Santos Pereira",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "17/06/1999",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Studio Jp",
    "busca": "marivania dos santos pereira"
  },
  {
    "nome": "Marivania Pereira Dos Santos",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "29/04/1981",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Rose Academia",
    "busca": "marivania pereira dos santos"
  },
  {
    "nome": "Mateus Rodrigues",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "02/07/2003",
    "camisa": "G",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "mateus rodrigues"
  },
  {
    "nome": "Matheus Da Silva Amaral",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "19/02/1996",
    "camisa": "G",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "matheus da silva amaral"
  },
  {
    "nome": "Matheus Heitor Lima De Souza Pantoja",
    "categoria": "Sub-13 - 1KM - até 13 anos",
    "grupo": "Kids 13 ANOS 1KM",
    "sexo": "Masculino",
    "nascimento": "12/11/2017",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "matheus heitor lima de souza pantoja"
  },
  {
    "nome": "Matheus Torres",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "18/07/1999",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "One Run E Equipe Vamos Pra Cima",
    "busca": "matheus torres"
  },
  {
    "nome": "Maycon Douglas Limeira Caldas",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "02/05/1990",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Academia Sparta",
    "busca": "maycon douglas limeira caldas"
  },
  {
    "nome": "Maykon Keverson Monteiro De Carvalho",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "11/04/2004",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Joubert",
    "busca": "maykon keverson monteiro de carvalho"
  },
  {
    "nome": "Maysa Kesia Da Silva Lima",
    "categoria": "Sub-13 - 1KM - até 13 anos",
    "grupo": "Kids 13 ANOS 1KM",
    "sexo": "Feminino",
    "nascimento": "08/12/2012",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Gogorunners",
    "busca": "maysa kesia da silva lima"
  },
  {
    "nome": "Meirielle",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "05/01/2003",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "meirielle"
  },
  {
    "nome": "Micaele Dias Oliveira",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "19/02/2002",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "micaele dias oliveira"
  },
  {
    "nome": "Milena Melo",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "26/04/2000",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Gogórunners",
    "busca": "milena melo"
  },
  {
    "nome": "Milene Da Silva Lima",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "01/10/1990",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Turma Do Joubert",
    "busca": "milene da silva lima"
  },
  {
    "nome": "Mirian Fernandes Cunha",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "27/03/1999",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "mirian fernandes cunha"
  },
  {
    "nome": "Murilo De Castro Souza",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "03/03/1998",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "murilo de castro souza"
  },
  {
    "nome": "Murilo Vasconcelos Nery",
    "categoria": "Sub-13 - 1KM - até 13 anos",
    "grupo": "Kids 13 ANOS 1KM",
    "sexo": "Masculino",
    "nascimento": "12/02/2022",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runnrs",
    "busca": "murilo vasconcelos nery"
  },
  {
    "nome": "Nágila Kamille Marques Caldas",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "24/06/1999",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Elite Run",
    "busca": "nagila kamille marques caldas"
  },
  {
    "nome": "Natalha Oliveira Do Nascimento",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "26/10/2002",
    "camisa": "GG",
    "representaEquipe": "Sim",
    "equipe": "Ibifit",
    "busca": "natalha oliveira do nascimento"
  },
  {
    "nome": "Náthally Vitória Albuquerque Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "27/02/2008",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "nathally vitoria albuquerque silva"
  },
  {
    "nome": "Neurilene De Souza Araújo",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "05/03/1981",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "neurilene de souza araujo"
  },
  {
    "nome": "Océlia Ferreira Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "28/01/1998",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Gogó Runners",
    "busca": "ocelia ferreira da silva"
  },
  {
    "nome": "Oziel De Souza Leite",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "03/07/1987",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Jp",
    "busca": "oziel de souza leite"
  },
  {
    "nome": "Patricia Arraes Sousa De Sousa",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "30/11/1986",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "patricia arraes sousa de sousa"
  },
  {
    "nome": "Paulo Henrique Abreu Barbosa",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "19/09/1996",
    "camisa": "G",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "paulo henrique abreu barbosa"
  },
  {
    "nome": "Pedro Henrique Alves Carvalho",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "24/12/2005",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "pedro henrique alves carvalho"
  },
  {
    "nome": "Pedro Luca Carvalho Da Silva",
    "categoria": "Sub-13 - 1KM - até 13 anos",
    "grupo": "Kids 13 ANOS 1KM",
    "sexo": "Masculino",
    "nascimento": "12/06/2017",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runneres",
    "busca": "pedro luca carvalho da silva"
  },
  {
    "nome": "Phyetro Assunção Da Silva",
    "categoria": "Sub-13 - 1KM - até 13 anos",
    "grupo": "Kids 13 ANOS 1KM",
    "sexo": "Feminino",
    "nascimento": "25/07/2012",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "phyetro assuncao da silva"
  },
  {
    "nome": "Pietro Gabriel De Paula",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Masculino",
    "nascimento": "03/08/2011",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "pietro gabriel de paula"
  },
  {
    "nome": "Rafael Luz Pereira",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "05/10/1999",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogórunners",
    "busca": "rafael luz pereira"
  },
  {
    "nome": "Rafaela Castro Da Conceição",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "08/05/2000",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "rafaela castro da conceicao"
  },
  {
    "nome": "Raimunda Ferreira Lima Oliveira",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "31/08/1984",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Studio Jump Alta Perfo",
    "busca": "raimunda ferreira lima oliveira"
  },
  {
    "nome": "Raimunda Rocha Soares",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "08/01/1988",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Run Delas",
    "busca": "raimunda rocha soares"
  },
  {
    "nome": "Raymara S Lima",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "08/11/1996",
    "camisa": "GG",
    "representaEquipe": "Sim",
    "equipe": "Jp",
    "busca": "raymara s lima"
  },
  {
    "nome": "Rhaisa Luthiane Da Silva Santos",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "01/12/1991",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Corredores De São José",
    "busca": "rhaisa luthiane da silva santos"
  },
  {
    "nome": "Ricardo Roger Santos Do Nascimento",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "23/05/1995",
    "camisa": "GG",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "ricardo roger santos do nascimento"
  },
  {
    "nome": "Rodrigo Braga Neves",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "13/06/2000",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "rodrigo braga neves"
  },
  {
    "nome": "Rodrigo Da Silva Alves",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "23/02/1991",
    "camisa": "XG",
    "representaEquipe": "Sim",
    "equipe": "Gogórunners",
    "busca": "rodrigo da silva alves"
  },
  {
    "nome": "Rodrigo Da Silva Dias",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "10/25/0095",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogorunners",
    "busca": "rodrigo da silva dias"
  },
  {
    "nome": "Rogério Machado Dos Santos",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "13/05/1987",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Estação Fitness",
    "busca": "rogerio machado dos santos"
  },
  {
    "nome": "Romário Lucas Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "21/09/1991",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Corre Rio",
    "busca": "romario lucas da silva"
  },
  {
    "nome": "Roreeon Araujo Santiago",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "20/08/2001",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Corre Rio",
    "busca": "roreeon araujo santiago"
  },
  {
    "nome": "Rosaly Da Silva Lima",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "22/12/1985",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Rum Delas",
    "busca": "rosaly da silva lima"
  },
  {
    "nome": "Rubia Carvalho Menezes Souza",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "29/07/1990",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Jp",
    "busca": "rubia carvalho menezes souza"
  },
  {
    "nome": "Rudney Souza Alves",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "02/05/1985",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "One Run",
    "busca": "rudney souza alves"
  },
  {
    "nome": "Ryan Pablo Da Silva Saturno",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "17/01/2010",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Não informado",
    "busca": "ryan pablo da silva saturno"
  },
  {
    "nome": "Sabrina Aires Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "20/02/1992",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "sabrina aires da silva"
  },
  {
    "nome": "Sabrina Freitas Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "08/05/2001",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "sabrina freitas silva"
  },
  {
    "nome": "Sabrina Sousa De Paula",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "03/10/2003",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "sabrina sousa de paula"
  },
  {
    "nome": "Salatiel Barbosa Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "10/06/1991",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "salatiel barbosa silva"
  },
  {
    "nome": "Samuel Costa Lima",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "17/01/1999",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "samuel costa lima"
  },
  {
    "nome": "Sara Vitória Silva Rocha",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "11/08/2000",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "sara vitoria silva rocha"
  },
  {
    "nome": "Sérgio Dos Reis Soares",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "01/09/1977",
    "camisa": "G",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "sergio dos reis soares"
  },
  {
    "nome": "Silvio Rayllan Da Costa Ferreira",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "05/01/2007",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Gogorunner",
    "busca": "silvio rayllan da costa ferreira"
  },
  {
    "nome": "Sirlene Ribeiro Da Costa",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "30/07/1986",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Dudu_Do_Para",
    "busca": "sirlene ribeiro da costa"
  },
  {
    "nome": "Sophia Da Silva Santos",
    "categoria": "Sub-17 - 2KM - até 17 anos",
    "grupo": "Kids 17 ANOS 2KM",
    "sexo": "Feminino",
    "nascimento": "13/08/2012",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Gogórunners",
    "busca": "sophia da silva santos"
  },
  {
    "nome": "Stefany Adelino De Jesus",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "15/08/1999",
    "camisa": "GG",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "stefany adelino de jesus"
  },
  {
    "nome": "Stefany Rodrigues",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "01/04/2002",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Corre Água Azul",
    "busca": "stefany rodrigues"
  },
  {
    "nome": "Suzana Vieira De Sousa",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "15/06/1987",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Studio Jump Alta Performance",
    "busca": "suzana vieira de sousa"
  },
  {
    "nome": "Tânia Rodrigues Santana",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "15/06/1980",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "tania rodrigues santana"
  },
  {
    "nome": "Tatiane Da Silva Santos",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "27/05/1997",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Dudu Do Pará",
    "busca": "tatiane da silva santos"
  },
  {
    "nome": "Tauã Ribeiro De Oliveira",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "02/08/2003",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "@Gogórunners",
    "busca": "taua ribeiro de oliveira"
  },
  {
    "nome": "Tenório",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "20/10/2001",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "One Run",
    "busca": "tenorio"
  },
  {
    "nome": "Thainara Oliveira De Sousa",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "09/03/1996",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Estação Fitness",
    "busca": "thainara oliveira de sousa"
  },
  {
    "nome": "Thales Teodoro Portela Quirino",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "24/04/2006",
    "camisa": "GG",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "thales teodoro portela quirino"
  },
  {
    "nome": "Thauane De Oliveira Lima",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "13/06/1997",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Joubert Jp",
    "busca": "thauane de oliveira lima"
  },
  {
    "nome": "Thaynara Lima De Souza",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "21/10/1994",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Performace",
    "busca": "thaynara lima de souza"
  },
  {
    "nome": "Thays Oliveira",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "08/09/2026",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Bw",
    "busca": "thays oliveira"
  },
  {
    "nome": "Tiago Silva De Andrade",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "15/05/1987",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Gogórunners",
    "busca": "tiago silva de andrade"
  },
  {
    "nome": "Uislei Carvalho",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "04/03/1993",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Gogórunners",
    "busca": "uislei carvalho"
  },
  {
    "nome": "Valdinei Ferro De Souza",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "19/01/1991",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Dudu Do Para",
    "busca": "valdinei ferro de souza"
  },
  {
    "nome": "Valdirene Da Silva Oliveira",
    "categoria": "Master B - 5KM - 50 anos acima",
    "grupo": "Master 50+",
    "sexo": "Feminino",
    "nascimento": "15/08/1970",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Studio Jump Alta Performance",
    "busca": "valdirene da silva oliveira"
  },
  {
    "nome": "Valdoanio Guimaraes De Almeida",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "16/06/1983",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "One Run",
    "busca": "valdoanio guimaraes de almeida"
  },
  {
    "nome": "Valter De Sousa Costa Maia Queiroz",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "31/05/1993",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "valter de sousa costa maia queiroz"
  },
  {
    "nome": "Vanda Da Silva Freitas",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "16/08/1981",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "vanda da silva freitas"
  },
  {
    "nome": "Vania Hamann",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Feminino",
    "nascimento": "07/02/1984",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "vania hamann"
  },
  {
    "nome": "Verônica Da Silva Rocha",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "02/06/1999",
    "camisa": "PP",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "veronica da silva rocha"
  },
  {
    "nome": "Vítor Lopes Dos Santos",
    "categoria": "Sub-13 - 1KM - até 13 anos",
    "grupo": "Kids 13 ANOS 1KM",
    "sexo": "Masculino",
    "nascimento": "11/01/2013",
    "camisa": "G",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "vitor lopes dos santos"
  },
  {
    "nome": "Vitor Miguel Bezerra Gomes",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "22/04/2003",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogórunnners",
    "busca": "vitor miguel bezerra gomes"
  },
  {
    "nome": "Warleys De Oliveira Júnior",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "23/09/1998",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Jobert",
    "busca": "warleys de oliveira junior"
  },
  {
    "nome": "Wellington De Oliveira Gomes",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "11/04/2001",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogorunners",
    "busca": "wellington de oliveira gomes"
  },
  {
    "nome": "Weslaine Maria Pereira De Carvalho",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "08/09/1993",
    "camisa": "P",
    "representaEquipe": "Sim",
    "equipe": "Rose Training Rum Delas",
    "busca": "weslaine maria pereira de carvalho"
  },
  {
    "nome": "Weslane Conceição Do Nascimento",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "03/09/1995",
    "camisa": "P",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "weslane conceicao do nascimento"
  },
  {
    "nome": "Weslene De Jesus Araújo",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "23/06/1998",
    "camisa": "PP",
    "representaEquipe": "Sim",
    "equipe": "Equipe Jp",
    "busca": "weslene de jesus araujo"
  },
  {
    "nome": "Wesley Gonçalves Soares",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "28/11/1993",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "wesley goncalves soares"
  },
  {
    "nome": "Wesley Macedo",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "26/11/1989",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Studio Jump Alta Performance",
    "busca": "wesley macedo"
  },
  {
    "nome": "Wesley Santos",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "16/01/2002",
    "camisa": "G",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "wesley santos"
  },
  {
    "nome": "Wesley Vagner Teixeira",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "27/01/1986",
    "camisa": "M",
    "representaEquipe": "Não",
    "equipe": "Não informado",
    "busca": "wesley vagner teixeira"
  },
  {
    "nome": "Weybe Dos Santos Ferreira",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "26/06/1992",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Gogo Runners",
    "busca": "weybe dos santos ferreira"
  },
  {
    "nome": "Wigvan De Lima Santana",
    "categoria": "Master A - 5KM - 40 a 49 anos",
    "grupo": "Master 40-49",
    "sexo": "Masculino",
    "nascimento": "26/02/1985",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Studio Jump Alta Performance",
    "busca": "wigvan de lima santana"
  },
  {
    "nome": "Wilker Freitas De Moraes",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "27/01/1997",
    "camisa": "G",
    "representaEquipe": "Sim",
    "equipe": "Dudu_Do_Pará",
    "busca": "wilker freitas de moraes"
  },
  {
    "nome": "Wliedson Gomes Da Silva",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Masculino",
    "nascimento": "12/07/2002",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Gogórunners",
    "busca": "wliedson gomes da silva"
  },
  {
    "nome": "Yara Kallinny Silva Marques",
    "categoria": "Elite 5KM - 18 a 39 anos",
    "grupo": "Elite",
    "sexo": "Feminino",
    "nascimento": "17/10/1998",
    "camisa": "M",
    "representaEquipe": "Sim",
    "equipe": "Jp",
    "busca": "yara kallinny silva marques"
  }
];
